# Dependencies
gems: [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Alec's Blog
tagline:          'Notes, ideas and random thoughts...'
description:      'Notes, ideas and random thougths...'
url:              http://talek.github.io/blog
baseurl:          http://talek.github.io/blog/
#baseurl:          "/"

author:
  name:           'Alexandru Tica'
  url:            https://twitter.com/alexandrutica

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
