# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Alec's Blog
tagline:          'Random Thoughts...'
description:      'Notes, random thougths, whatever...'
url:              http://talek.github.io/blog
baseurl:          /blog/
#baseurl:          "/"

author:
  name:           'Alexandru Tica'
  url:            https://twitter.com/alexandrutica

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
